// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateParams } from "./types/realfin/oracle/v1/tx";
import { MsgCreatePrice } from "./types/realfin/oracle/v1/tx";
import { MsgUpdatePrice } from "./types/realfin/oracle/v1/tx";
import { MsgDeletePrice } from "./types/realfin/oracle/v1/tx";

import { Params as typeParams} from "./types"
import { Price as typePrice} from "./types"

export { MsgUpdateParams, MsgCreatePrice, MsgUpdatePrice, MsgDeletePrice };

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreatePriceParams = {
  value: MsgCreatePrice,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdatePriceParams = {
  value: MsgUpdatePrice,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeletePriceParams = {
  value: MsgDeletePrice,
  fee?: StdFee,
  memo?: string
};


type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type msgCreatePriceParams = {
  value: MsgCreatePrice,
};

type msgUpdatePriceParams = {
  value: MsgUpdatePrice,
};

type msgDeletePriceParams = {
  value: MsgDeletePrice,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreatePrice({ value, fee, memo }: sendMsgCreatePriceParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreatePrice: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgCreatePrice({ value: MsgCreatePrice.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreatePrice: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdatePrice({ value, fee, memo }: sendMsgUpdatePriceParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdatePrice: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdatePrice({ value: MsgUpdatePrice.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdatePrice: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeletePrice({ value, fee, memo }: sendMsgDeletePriceParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeletePrice: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgDeletePrice({ value: MsgDeletePrice.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeletePrice: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/realfin.oracle.v1.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		msgCreatePrice({ value }: msgCreatePriceParams): EncodeObject {
			try {
				return { typeUrl: "/realfin.oracle.v1.MsgCreatePrice", value: MsgCreatePrice.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreatePrice: Could not create message: ' + e.message)
			}
		},
		
		msgUpdatePrice({ value }: msgUpdatePriceParams): EncodeObject {
			try {
				return { typeUrl: "/realfin.oracle.v1.MsgUpdatePrice", value: MsgUpdatePrice.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdatePrice: Could not create message: ' + e.message)
			}
		},
		
		msgDeletePrice({ value }: msgDeletePriceParams): EncodeObject {
			try {
				return { typeUrl: "/realfin.oracle.v1.MsgDeletePrice", value: MsgDeletePrice.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeletePrice: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Params: getStructure(typeParams.fromPartial({})),
						Price: getStructure(typePrice.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			RealfinOracleV_1: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;