// Generated by Ignite ignite.com/cli

import { SigningStargateClient, DeliverTxResponse, StdFee } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateParams } from "./types/realfin/realestate/v1/tx";
import { MsgCreateRate } from "./types/realfin/realestate/v1/tx";
import { MsgUpdateRate } from "./types/realfin/realestate/v1/tx";
import { MsgDeleteRate } from "./types/realfin/realestate/v1/tx";

import { Params as typeParams} from "./types"
import { Rate as typeRate} from "./types"

export { MsgUpdateParams, MsgCreateRate, MsgUpdateRate, MsgDeleteRate };

type sendMsgUpdateParamsParams = {
  value: MsgUpdateParams,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateRateParams = {
  value: MsgCreateRate,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateRateParams = {
  value: MsgUpdateRate,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteRateParams = {
  value: MsgDeleteRate,
  fee?: StdFee,
  memo?: string
};


type msgUpdateParamsParams = {
  value: MsgUpdateParams,
};

type msgCreateRateParams = {
  value: MsgCreateRate,
};

type msgUpdateRateParams = {
  value: MsgUpdateRate,
};

type msgDeleteRateParams = {
  value: MsgDeleteRate,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgUpdateParams({ value, fee, memo }: sendMsgUpdateParamsParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateParams: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateParams({ value: MsgUpdateParams.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateParams: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateRate({ value, fee, memo }: sendMsgCreateRateParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateRate: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgCreateRate({ value: MsgCreateRate.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateRate: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUpdateRate({ value, fee, memo }: sendMsgUpdateRateParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateRate: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgUpdateRate({ value: MsgUpdateRate.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateRate: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteRate({ value, fee, memo }: sendMsgDeleteRateParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteRate: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry});
				let msg = this.msgDeleteRate({ value: MsgDeleteRate.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteRate: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateParams({ value }: msgUpdateParamsParams): EncodeObject {
			try {
				return { typeUrl: "/realfin.realestate.v1.MsgUpdateParams", value: MsgUpdateParams.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateParams: Could not create message: ' + e.message)
			}
		},
		
		msgCreateRate({ value }: msgCreateRateParams): EncodeObject {
			try {
				return { typeUrl: "/realfin.realestate.v1.MsgCreateRate", value: MsgCreateRate.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateRate: Could not create message: ' + e.message)
			}
		},
		
		msgUpdateRate({ value }: msgUpdateRateParams): EncodeObject {
			try {
				return { typeUrl: "/realfin.realestate.v1.MsgUpdateRate", value: MsgUpdateRate.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateRate: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteRate({ value }: msgDeleteRateParams): EncodeObject {
			try {
				return { typeUrl: "/realfin.realestate.v1.MsgDeleteRate", value: MsgDeleteRate.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteRate: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						Params: getStructure(typeParams.fromPartial({})),
						Rate: getStructure(typeRate.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const IgntModule = (test: IgniteClient) => {
	return {
		module: {
			RealfinRealestateV_1: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default IgntModule;